version: '3'
services:
  mqtt:
    image: fstehle/rpi-mosquitto
    network_mode: host
    restart: always

  ble:
    build: ./docker/ble
    network_mode: host
    privileged: true
    restart: always
    volumes:
            - "./ble:/code" 
            - "./common:/common" 

  hub:
    build: ./docker/hub
    #command: "tail -f /dev/null"
    network_mode: host
    restart: always
    volumes:
            - "./hub:/code" 
            - "./common:/common" 
  exta:
    build: ./docker/exta
#    command: "tail -f /dev/null"
    network_mode: host
    restart: always
    volumes:
            - "./exta:/usr/src/app" 
            - "./common:/common" 

  crouton:
    build: ./docker/crouton
    #command: "tail -f /dev/null"
    network_mode: host
    restart: always
#    user: node

#    environment:
      #- NODE_ENV=production
 #   command: "sleep infinity"
    command: "grunt"
    volumes:
            - "./crouton:/home/node/app" 
            - "./common:/common" 

